# Generated by Django 4.2.5 on 2023-09-19 06:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls')], max_length=6)),
                ('productName', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField(max_length=500)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('watchCount', models.IntegerField(default=0)),
            ],
        ),
    ]
