# Generated by Django 4.2.5 on 2023-09-19 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='images',
        ),
        migrations.AddField(
            model_name='productimage',
            name='productImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.productimages'),
        ),
    ]
