# Generated by Django 4.2.5 on 2023-09-19 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_productimages_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='productImage',
        ),
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.product'),
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
