# Generated by Django 4.2.5 on 2023-10-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_productbrand_created_at_productcategory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='detail',
            field=models.CharField(max_length=50),
        ),
    ]
